all: libnative.dylib tmp.native.h
	@:

libnative.dylib: native.c
	gcc -dynamiclib -o libnative.dylib native.c

native.so: native.o
	gcc -shared -fPIC -o native.so native.o -lc

native.o: native.c
	gcc -c -fPIC -o native.o native.c

tmp.native.h: native.h
	cp native.h tmp.native.h

.PHONY: all
