all: native.dll templates.dll tmp.native.h

native.dll: native.obj utf8.obj
	cl /LD native.obj utf8.obj

native.obj: native.c
	cl /c native.c

utf8.obj: utf8.c
	cl /c utf8.c

templates.dll: templates.obj
	cl /LD templates.obj

templates.obj: templates.cpp
	cl /c templates.cpp

tmp.native.h: native.h
	cp native.h tmp.native.h

.PHONY: all
