all: libnative.so libtemplates.so tmp.native.h
	@:

libnative.so: native.o utf8.o
	gcc -shared -fPIC -o libnative.so native.o utf8.o -lc

native.o: native.c
	gcc -c -fPIC -o native.o native.c

utf8.o: utf8.c
	gcc -c -fPIC -o utf8.o utf8.c

libtemplates.so: templates.o
	g++ -shared -fPIC -o libtemplates.so templates.o -lc

templates.o: templates.cpp
	g++ -std=c++11 -c -fPIC -o templates.o templates.cpp

tmp.native.h: native.h
	cp native.h tmp.native.h

.PHONY: all
