all: libnative.dylib libnative.a libtemplates.dylib libtemplates.a tmp.native.h
	@:

libnative.a: native.o utf8.o
	ar -rcs libnative.a native.o utf8.o

native.o: native.c
	gcc -o native.o -c native.c

utf8.o: utf8.c
	gcc -o utf8.o -c utf8.c

libnative.dylib: native.c utf8.c
	gcc -dynamiclib -o libnative.dylib native.c utf8.c

libtemplates.a: templates.o
	ar -rcs libtemplates.a templates.o

templates.o: templates.cpp
	g++ -std=c++11 -o templates.o -c templates.cpp

libtemplates.dylib: templates.cpp
	g++ -std=c++11 -dynamiclib -o libtemplates.dylib templates.cpp

tmp.native.h: native.h
	cp native.h tmp.native.h

.PHONY: all
