name: Build Windows

on: [push, pull_request]

jobs:
  test-hxcpp:
    runs-on: windows-latest
    steps:
    - name: Install Haxe (4.0.3)
      uses: haxeui/haxeui-core/.github/actions/haxe@master
      with:
        haxe-version: 4.0.3

    - name: Checkout ammer
      uses: actions/checkout@v2
      with:
        path: "ammer"

    - name: Set up haxelibs
      run: |
        haxelib dev ammer ammer
        haxelib install utest

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build native library
      run: |
        cd ammer/tests/native
        nmake /f Makefile.win

    - name: Install hxcpp
      run: |
        haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
        cd `haxelib path hxcpp | head -n 1`
        cd tools/hxcpp
        haxe compile.hxml

    - name: Compile tests
      run: |
        cd ammer/tests
        haxe build-cpp.hxml
        cp native/native.dll bin/cpp
        cp native/templates.dll bin/cpp

    - name: Run tests
      run: |
        cd ammer/tests/bin/cpp
        ./Main
